/* Generated By:JavaCC: Do not edit this line. ARQParserConstants.java */
/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package org.apache.jena.sparql.lang.arq.javacc ;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ARQParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int WS = 7;
  /** RegularExpression Id. */
  int WSC = 8;
  /** RegularExpression Id. */
  int BOM = 9;
  /** RegularExpression Id. */
  int IRIref = 10;
  /** RegularExpression Id. */
  int PNAME_NS = 11;
  /** RegularExpression Id. */
  int PNAME_LN = 12;
  /** RegularExpression Id. */
  int BLANK_NODE_LABEL = 13;
  /** RegularExpression Id. */
  int VAR1 = 14;
  /** RegularExpression Id. */
  int VAR2 = 15;
  /** RegularExpression Id. */
  int LANG_DIR = 16;
  /** RegularExpression Id. */
  int A2Z = 17;
  /** RegularExpression Id. */
  int A2ZN = 18;
  /** RegularExpression Id. */
  int KW_A = 19;
  /** RegularExpression Id. */
  int BASE = 20;
  /** RegularExpression Id. */
  int PREFIX = 21;
  /** RegularExpression Id. */
  int VERSION = 22;
  /** RegularExpression Id. */
  int SELECT = 23;
  /** RegularExpression Id. */
  int DISTINCT = 24;
  /** RegularExpression Id. */
  int REDUCED = 25;
  /** RegularExpression Id. */
  int JSON = 26;
  /** RegularExpression Id. */
  int DESCRIBE = 27;
  /** RegularExpression Id. */
  int CONSTRUCT = 28;
  /** RegularExpression Id. */
  int ASK = 29;
  /** RegularExpression Id. */
  int LIMIT = 30;
  /** RegularExpression Id. */
  int OFFSET = 31;
  /** RegularExpression Id. */
  int ORDER = 32;
  /** RegularExpression Id. */
  int BY = 33;
  /** RegularExpression Id. */
  int VALUES = 34;
  /** RegularExpression Id. */
  int UNDEF = 35;
  /** RegularExpression Id. */
  int ASC = 36;
  /** RegularExpression Id. */
  int DESC = 37;
  /** RegularExpression Id. */
  int NAMED = 38;
  /** RegularExpression Id. */
  int FROM = 39;
  /** RegularExpression Id. */
  int WHERE = 40;
  /** RegularExpression Id. */
  int AND = 41;
  /** RegularExpression Id. */
  int GRAPH = 42;
  /** RegularExpression Id. */
  int OPTIONAL = 43;
  /** RegularExpression Id. */
  int UNION = 44;
  /** RegularExpression Id. */
  int MINUS_P = 45;
  /** RegularExpression Id. */
  int BIND = 46;
  /** RegularExpression Id. */
  int SERVICE = 47;
  /** RegularExpression Id. */
  int LET = 48;
  /** RegularExpression Id. */
  int LATERAL = 49;
  /** RegularExpression Id. */
  int SEMIJOIN = 50;
  /** RegularExpression Id. */
  int ANTIJOIN = 51;
  /** RegularExpression Id. */
  int UNFOLD = 52;
  /** RegularExpression Id. */
  int SIMILARITYJOIN = 53;
  /** RegularExpression Id. */
  int FUSEJOIN = 54;
  /** RegularExpression Id. */
  int TRIPLE = 55;
  /** RegularExpression Id. */
  int IS_TRIPLE = 56;
  /** RegularExpression Id. */
  int SUBJECT = 57;
  /** RegularExpression Id. */
  int PREDICATE = 58;
  /** RegularExpression Id. */
  int OBJECT = 59;
  /** RegularExpression Id. */
  int EXISTS = 60;
  /** RegularExpression Id. */
  int NOT = 61;
  /** RegularExpression Id. */
  int AS = 62;
  /** RegularExpression Id. */
  int GROUP = 63;
  /** RegularExpression Id. */
  int HAVING = 64;
  /** RegularExpression Id. */
  int SEPARATOR = 65;
  /** RegularExpression Id. */
  int AGG = 66;
  /** RegularExpression Id. */
  int COUNT = 67;
  /** RegularExpression Id. */
  int MIN = 68;
  /** RegularExpression Id. */
  int MAX = 69;
  /** RegularExpression Id. */
  int SUM = 70;
  /** RegularExpression Id. */
  int AVG = 71;
  /** RegularExpression Id. */
  int MEDIAN = 72;
  /** RegularExpression Id. */
  int MODE = 73;
  /** RegularExpression Id. */
  int STDEV = 74;
  /** RegularExpression Id. */
  int STDEV_SAMP = 75;
  /** RegularExpression Id. */
  int STDEV_POP = 76;
  /** RegularExpression Id. */
  int VARIANCE = 77;
  /** RegularExpression Id. */
  int VAR_SAMP = 78;
  /** RegularExpression Id. */
  int VAR_POP = 79;
  /** RegularExpression Id. */
  int FOLD = 80;
  /** RegularExpression Id. */
  int SAMPLE = 81;
  /** RegularExpression Id. */
  int GROUP_CONCAT = 82;
  /** RegularExpression Id. */
  int FILTER = 83;
  /** RegularExpression Id. */
  int BOUND = 84;
  /** RegularExpression Id. */
  int COALESCE = 85;
  /** RegularExpression Id. */
  int IN = 86;
  /** RegularExpression Id. */
  int IF = 87;
  /** RegularExpression Id. */
  int BNODE = 88;
  /** RegularExpression Id. */
  int IRI = 89;
  /** RegularExpression Id. */
  int URI = 90;
  /** RegularExpression Id. */
  int EBV = 91;
  /** RegularExpression Id. */
  int CAST = 92;
  /** RegularExpression Id. */
  int CALL = 93;
  /** RegularExpression Id. */
  int MULTI = 94;
  /** RegularExpression Id. */
  int SHORTEST = 95;
  /** RegularExpression Id. */
  int STR = 96;
  /** RegularExpression Id. */
  int STRLANG = 97;
  /** RegularExpression Id. */
  int STRLANGDIR = 98;
  /** RegularExpression Id. */
  int STRDT = 99;
  /** RegularExpression Id. */
  int DTYPE = 100;
  /** RegularExpression Id. */
  int LANG = 101;
  /** RegularExpression Id. */
  int LANGMATCHES = 102;
  /** RegularExpression Id. */
  int LANGDIR = 103;
  /** RegularExpression Id. */
  int IS_URI = 104;
  /** RegularExpression Id. */
  int IS_IRI = 105;
  /** RegularExpression Id. */
  int IS_BLANK = 106;
  /** RegularExpression Id. */
  int IS_LITERAL = 107;
  /** RegularExpression Id. */
  int IS_NUMERIC = 108;
  /** RegularExpression Id. */
  int HAS_LANG = 109;
  /** RegularExpression Id. */
  int HAS_LANGDIR = 110;
  /** RegularExpression Id. */
  int REGEX = 111;
  /** RegularExpression Id. */
  int SAME_TERM = 112;
  /** RegularExpression Id. */
  int SAME_VALUE = 113;
  /** RegularExpression Id. */
  int RAND = 114;
  /** RegularExpression Id. */
  int ABS = 115;
  /** RegularExpression Id. */
  int CEIL = 116;
  /** RegularExpression Id. */
  int FLOOR = 117;
  /** RegularExpression Id. */
  int ROUND = 118;
  /** RegularExpression Id. */
  int MOD = 119;
  /** RegularExpression Id. */
  int IDIV = 120;
  /** RegularExpression Id. */
  int CONCAT = 121;
  /** RegularExpression Id. */
  int SUBSTR = 122;
  /** RegularExpression Id. */
  int STRLEN = 123;
  /** RegularExpression Id. */
  int REPLACE = 124;
  /** RegularExpression Id. */
  int UCASE = 125;
  /** RegularExpression Id. */
  int LCASE = 126;
  /** RegularExpression Id. */
  int ENCODE_FOR_URI = 127;
  /** RegularExpression Id. */
  int CONTAINS = 128;
  /** RegularExpression Id. */
  int STRSTARTS = 129;
  /** RegularExpression Id. */
  int STRENDS = 130;
  /** RegularExpression Id. */
  int STRBEFORE = 131;
  /** RegularExpression Id. */
  int STRAFTER = 132;
  /** RegularExpression Id. */
  int YEAR = 133;
  /** RegularExpression Id. */
  int MONTH = 134;
  /** RegularExpression Id. */
  int DAY = 135;
  /** RegularExpression Id. */
  int HOURS = 136;
  /** RegularExpression Id. */
  int MINUTES = 137;
  /** RegularExpression Id. */
  int SECONDS = 138;
  /** RegularExpression Id. */
  int TIMEZONE = 139;
  /** RegularExpression Id. */
  int TZ = 140;
  /** RegularExpression Id. */
  int ADJUST = 141;
  /** RegularExpression Id. */
  int NOW = 142;
  /** RegularExpression Id. */
  int UUID = 143;
  /** RegularExpression Id. */
  int STRUUID = 144;
  /** RegularExpression Id. */
  int MD5 = 145;
  /** RegularExpression Id. */
  int SHA1 = 146;
  /** RegularExpression Id. */
  int SHA224 = 147;
  /** RegularExpression Id. */
  int SHA256 = 148;
  /** RegularExpression Id. */
  int SHA384 = 149;
  /** RegularExpression Id. */
  int SHA512 = 150;
  /** RegularExpression Id. */
  int TRUE = 151;
  /** RegularExpression Id. */
  int FALSE = 152;
  /** RegularExpression Id. */
  int DATA = 153;
  /** RegularExpression Id. */
  int INSERT = 154;
  /** RegularExpression Id. */
  int DELETE = 155;
  /** RegularExpression Id. */
  int INSERT_DATA = 156;
  /** RegularExpression Id. */
  int DELETE_DATA = 157;
  /** RegularExpression Id. */
  int DELETE_WHERE = 158;
  /** RegularExpression Id. */
  int LOAD = 159;
  /** RegularExpression Id. */
  int CLEAR = 160;
  /** RegularExpression Id. */
  int CREATE = 161;
  /** RegularExpression Id. */
  int ADD = 162;
  /** RegularExpression Id. */
  int MOVE = 163;
  /** RegularExpression Id. */
  int COPY = 164;
  /** RegularExpression Id. */
  int META = 165;
  /** RegularExpression Id. */
  int SILENT = 166;
  /** RegularExpression Id. */
  int DROP = 167;
  /** RegularExpression Id. */
  int INTO = 168;
  /** RegularExpression Id. */
  int TO = 169;
  /** RegularExpression Id. */
  int DFT = 170;
  /** RegularExpression Id. */
  int ALL = 171;
  /** RegularExpression Id. */
  int WITH = 172;
  /** RegularExpression Id. */
  int USING = 173;
  /** RegularExpression Id. */
  int DIGITS = 174;
  /** RegularExpression Id. */
  int INTEGER = 175;
  /** RegularExpression Id. */
  int DECIMAL = 176;
  /** RegularExpression Id. */
  int DOUBLE = 177;
  /** RegularExpression Id. */
  int EXPONENT = 178;
  /** RegularExpression Id. */
  int INTEGER_POSITIVE = 179;
  /** RegularExpression Id. */
  int DECIMAL_POSITIVE = 180;
  /** RegularExpression Id. */
  int DOUBLE_POSITIVE = 181;
  /** RegularExpression Id. */
  int INTEGER_NEGATIVE = 182;
  /** RegularExpression Id. */
  int DECIMAL_NEGATIVE = 183;
  /** RegularExpression Id. */
  int DOUBLE_NEGATIVE = 184;
  /** RegularExpression Id. */
  int QUOTE_3D = 185;
  /** RegularExpression Id. */
  int QUOTE_3S = 186;
  /** RegularExpression Id. */
  int ECHAR = 187;
  /** RegularExpression Id. */
  int UCHAR = 188;
  /** RegularExpression Id. */
  int UCHAR4 = 189;
  /** RegularExpression Id. */
  int UCHAR8 = 190;
  /** RegularExpression Id. */
  int STRING_LITERAL1 = 191;
  /** RegularExpression Id. */
  int STRING_LITERAL2 = 192;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG1 = 193;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG2 = 194;
  /** RegularExpression Id. */
  int LPAREN = 195;
  /** RegularExpression Id. */
  int RPAREN = 196;
  /** RegularExpression Id. */
  int NIL = 197;
  /** RegularExpression Id. */
  int LBRACE = 198;
  /** RegularExpression Id. */
  int RBRACE = 199;
  /** RegularExpression Id. */
  int LBRACKET = 200;
  /** RegularExpression Id. */
  int RBRACKET = 201;
  /** RegularExpression Id. */
  int ANON = 202;
  /** RegularExpression Id. */
  int SEMICOLON = 203;
  /** RegularExpression Id. */
  int COMMA = 204;
  /** RegularExpression Id. */
  int DOT = 205;
  /** RegularExpression Id. */
  int EQ = 206;
  /** RegularExpression Id. */
  int NE = 207;
  /** RegularExpression Id. */
  int GT = 208;
  /** RegularExpression Id. */
  int LT = 209;
  /** RegularExpression Id. */
  int LE = 210;
  /** RegularExpression Id. */
  int GE = 211;
  /** RegularExpression Id. */
  int L_TRIPLE = 212;
  /** RegularExpression Id. */
  int R_TRIPLE = 213;
  /** RegularExpression Id. */
  int LT2 = 214;
  /** RegularExpression Id. */
  int GT2 = 215;
  /** RegularExpression Id. */
  int L_ANN = 216;
  /** RegularExpression Id. */
  int R_ANN = 217;
  /** RegularExpression Id. */
  int TILDE = 218;
  /** RegularExpression Id. */
  int BANG = 219;
  /** RegularExpression Id. */
  int COLON = 220;
  /** RegularExpression Id. */
  int SC_OR = 221;
  /** RegularExpression Id. */
  int SC_AND = 222;
  /** RegularExpression Id. */
  int PLUS = 223;
  /** RegularExpression Id. */
  int MINUS = 224;
  /** RegularExpression Id. */
  int STAR = 225;
  /** RegularExpression Id. */
  int SLASH = 226;
  /** RegularExpression Id. */
  int DATATYPE = 227;
  /** RegularExpression Id. */
  int AT = 228;
  /** RegularExpression Id. */
  int ASSIGN = 229;
  /** RegularExpression Id. */
  int VBAR = 230;
  /** RegularExpression Id. */
  int CARAT = 231;
  /** RegularExpression Id. */
  int QMARK = 232;
  /** RegularExpression Id. */
  int SURROGATE_PAIR = 233;
  /** RegularExpression Id. */
  int PN_CHARS_BASE = 234;
  /** RegularExpression Id. */
  int PN_CHARS_U = 235;
  /** RegularExpression Id. */
  int PN_CHARS = 236;
  /** RegularExpression Id. */
  int PN_PREFIX = 237;
  /** RegularExpression Id. */
  int PN_LOCAL = 238;
  /** RegularExpression Id. */
  int VARNAME = 239;
  /** RegularExpression Id. */
  int PN_LOCAL_ESC = 240;
  /** RegularExpression Id. */
  int PLX = 241;
  /** RegularExpression Id. */
  int HEX = 242;
  /** RegularExpression Id. */
  int PERCENT = 243;
  /** RegularExpression Id. */
  int UNKNOWN = 244;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<WS>",
    "<WSC>",
    "\"\\ufeff\"",
    "<IRIref>",
    "<PNAME_NS>",
    "<PNAME_LN>",
    "<BLANK_NODE_LABEL>",
    "<VAR1>",
    "<VAR2>",
    "<LANG_DIR>",
    "<A2Z>",
    "<A2ZN>",
    "\"a\"",
    "\"base\"",
    "\"prefix\"",
    "\"version\"",
    "\"select\"",
    "\"distinct\"",
    "\"reduced\"",
    "\"json\"",
    "\"describe\"",
    "\"construct\"",
    "\"ask\"",
    "\"limit\"",
    "\"offset\"",
    "\"order\"",
    "\"by\"",
    "\"values\"",
    "\"undef\"",
    "\"asc\"",
    "\"desc\"",
    "\"named\"",
    "\"from\"",
    "\"where\"",
    "\"and\"",
    "\"graph\"",
    "\"optional\"",
    "\"union\"",
    "\"minus\"",
    "\"bind\"",
    "\"service\"",
    "\"LET\"",
    "\"lateral\"",
    "\"semijoin\"",
    "\"antijoin\"",
    "\"unfold\"",
    "\"DIVJOIN\"",
    "\"FUSEJOIN\"",
    "\"TRIPLE\"",
    "\"isTRIPLE\"",
    "\"SUBJECT\"",
    "\"PREDICATE\"",
    "\"OBJECT\"",
    "\"exists\"",
    "\"not\"",
    "\"as\"",
    "\"group\"",
    "\"having\"",
    "\"separator\"",
    "\"agg\"",
    "\"count\"",
    "\"min\"",
    "\"max\"",
    "\"sum\"",
    "\"avg\"",
    "\"median\"",
    "\"mode\"",
    "\"stdev\"",
    "\"stdev_samp\"",
    "\"stdev_pop\"",
    "\"variance\"",
    "\"var_samp\"",
    "\"var_pop\"",
    "\"fold\"",
    "\"sample\"",
    "\"group_concat\"",
    "\"filter\"",
    "\"bound\"",
    "\"coalesce\"",
    "\"in\"",
    "\"if\"",
    "\"bnode\"",
    "\"iri\"",
    "\"uri\"",
    "\"EBV\"",
    "\"cast\"",
    "\"call\"",
    "\"multi\"",
    "\"shortest\"",
    "\"str\"",
    "\"strlang\"",
    "\"strlangdir\"",
    "\"strdt\"",
    "\"datatype\"",
    "\"lang\"",
    "\"langmatches\"",
    "\"langdir\"",
    "\"isURI\"",
    "\"isIRI\"",
    "\"isBlank\"",
    "\"isLiteral\"",
    "\"isNumeric\"",
    "\"hasLang\"",
    "\"hasLangDir\"",
    "\"regex\"",
    "\"sameTerm\"",
    "\"sameValue\"",
    "\"RAND\"",
    "\"ABS\"",
    "\"CEIL\"",
    "\"FLOOR\"",
    "\"ROUND\"",
    "\"MOD\"",
    "\"IDIV\"",
    "\"CONCAT\"",
    "\"SUBSTR\"",
    "\"STRLEN\"",
    "\"REPLACE\"",
    "\"UCASE\"",
    "\"LCASE\"",
    "\"ENCODE_FOR_URI\"",
    "\"CONTAINS\"",
    "\"STRSTARTS\"",
    "\"STRENDS\"",
    "\"STRBEFORE\"",
    "\"STRAFTER\"",
    "\"YEAR\"",
    "\"MONTH\"",
    "\"DAY\"",
    "\"HOURS\"",
    "\"MINUTES\"",
    "\"SECONDS\"",
    "\"TIMEZONE\"",
    "\"TZ\"",
    "\"ADJUST\"",
    "\"NOW\"",
    "\"UUID\"",
    "\"STRUUID\"",
    "\"MD5\"",
    "\"SHA1\"",
    "\"SHA224\"",
    "\"SHA256\"",
    "\"SHA384\"",
    "\"SHA512\"",
    "\"true\"",
    "\"false\"",
    "\"data\"",
    "\"insert\"",
    "\"delete\"",
    "<INSERT_DATA>",
    "<DELETE_DATA>",
    "<DELETE_WHERE>",
    "\"load\"",
    "\"clear\"",
    "\"create\"",
    "\"add\"",
    "\"move\"",
    "\"copy\"",
    "\"meta\"",
    "\"silent\"",
    "\"drop\"",
    "\"into\"",
    "\"to\"",
    "\"default\"",
    "\"all\"",
    "\"with\"",
    "\"using\"",
    "<DIGITS>",
    "<INTEGER>",
    "<DECIMAL>",
    "<DOUBLE>",
    "<EXPONENT>",
    "<INTEGER_POSITIVE>",
    "<DECIMAL_POSITIVE>",
    "<DOUBLE_POSITIVE>",
    "<INTEGER_NEGATIVE>",
    "<DECIMAL_NEGATIVE>",
    "<DOUBLE_NEGATIVE>",
    "\"\\\"\\\"\\\"\"",
    "\"\\\'\\\'\\\'\"",
    "<ECHAR>",
    "<UCHAR>",
    "<UCHAR4>",
    "<UCHAR8>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<STRING_LITERAL_LONG1>",
    "<STRING_LITERAL_LONG2>",
    "\"(\"",
    "\")\"",
    "<NIL>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<ANON>",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"<<(\"",
    "\")>>\"",
    "\"<<\"",
    "\">>\"",
    "\"{|\"",
    "\"|}\"",
    "\"~\"",
    "\"!\"",
    "\":\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^^\"",
    "\"@\"",
    "\":=\"",
    "\"|\"",
    "\"^\"",
    "\"?\"",
    "<SURROGATE_PAIR>",
    "<PN_CHARS_BASE>",
    "<PN_CHARS_U>",
    "<PN_CHARS>",
    "<PN_PREFIX>",
    "<PN_LOCAL>",
    "<VARNAME>",
    "<PN_LOCAL_ESC>",
    "<PLX>",
    "<HEX>",
    "<PERCENT>",
    "<UNKNOWN>",
  };

}
