PREFIX ag: <https://w3id.org/circular-factory/ontology/angle-grinder#>
PREFIX im: <https://w3id.org/circular-factory/ontology/inspection-measurement#>
PREFIX om: <http://www.ontology-of-units-of-measure.org/resource/om-2/>
PREFIX uq: <http://example.org/ontology/uncertainty#>

SELECT ?driveGear ?spindleGear WHERE {
  { ?driveGear a ag:DriveGear ;
      im:hasHardCharacteristic ?hardcharA .
    ?hardcharA im:isMeasuredBy ?measA .
    ?measA om:hasUnit om:HardnessVickers ;
      uq:representedBy ?rvA .
    ?rvA uq:hasDomain uq:nonNegativeDouble ;
      uq:hasDistribution ?distA . }

  SIMILARITYJOIN(?distA, ?distB, 0.3, 0.05)

  { ?spindleGear a ag:SpindleGear ;
      im:hasHardCharacteristic ?hardcharB .
    ?hardcharB im:isMeasuredBy ?measB .
    ?measB om:hasUnit om:HardnessVickers ;
      uq:representedBy ?rvB .
    ?rvB uq:hasDomain uq:nonNegativeDouble ;
      uq:hasDistribution ?distB . }
}
