package org.apache.jena.probsparql;

import org.apache.jena.query.*;
import org.apache.jena.rdf.model.*;

import java.io.*;
import java.util.*;

/**
 * Exp 4.5 — Dirichlet Distribution Standalone Demonstration
 *
 * <p>Demonstrates that ProbSPARQL can handle Dirichlet-encoded material
 * compositions with realistic query patterns.</p>
 *
 * <p>Loads the Dirichlet dataset generated by
 * {@code generate_dirichlet_dataset.py} and runs two queries:</p>
 *
 * <ul>
 *   <li>Q-dir-1: Find anomalous compositions (JSD > threshold)</li>
 *   <li>Q-dir-2: Get mean composition vector for each component</li>
 * </ul>
 *
 * <p>Also runs the same queries on an in-memory dataset to ensure
 * correctness even if the TTL file is not yet generated.
 *
 * <p>Output CSV: {@code exp4_dirichlet_demo.csv}
 * <pre>Query,Source,ResultCount,SampleResult,Status</pre>
 *
 * Usage:
 *   mvn exec:java -Dexec.mainClass="org.apache.jena.probsparql.Exp4DirichletDemo" \
 *       -Dexec.args="--data-dir benchmark/data"
 */
public class Exp4DirichletDemo {

    private static final String NS_EX  = "http://example.org/data/";
    private static final String NS_UQ  = "http://example.org/ontology/uncertainty#";
    private static final String NS_CFM = "http://example.org/ontology/cfm#";

    // Q-dir-1: Anomalous compositions (high JSD between measured and expected)
    private static final String Q_DIR_1 = """
        PREFIX cfm:  <http://example.org/ontology/cfm#>
        PREFIX prob: <http://probsparql.org/function#>
        SELECT ?component ?divergence WHERE {
            ?component cfm:hasMeasuredComposition ?measured ;
                       cfm:hasExpectedComposition ?expected .
            BIND(prob:jsd(?measured, ?expected) AS ?divergence)
            FILTER(?divergence > 0.05)
        }
        ORDER BY DESC(?divergence)
        LIMIT 10""";

    // Q-dir-2: Mean composition vector for each component
    private static final String Q_DIR_2 = """
        PREFIX cfm:  <http://example.org/ontology/cfm#>
        PREFIX prob: <http://probsparql.org/function#>
        SELECT ?component ?meanComposition WHERE {
            ?component cfm:hasMeasuredComposition ?dist .
            BIND(prob:mean(?dist) AS ?meanComposition)
        }
        LIMIT 10""";

    // Q-dir-3: CDF on Dirichlet (fraction below threshold)
    private static final String Q_DIR_3 = """
        PREFIX cfm:  <http://example.org/ontology/cfm#>
        PREFIX prob: <http://probsparql.org/function#>
        SELECT ?component ?prob WHERE {
            ?component cfm:hasMeasuredComposition ?dist .
            BIND(prob:cdf(?dist, 0.4) AS ?prob)
            FILTER(?prob > 0.5)
        }
        LIMIT 10""";

    public static void main(String[] args) throws Exception {
        ProbSPARQL.init();

        String outputDir = "benchmark/results/exp4";
        String dataDir   = "benchmark/data";
        for (int i = 0; i < args.length; i++) {
            if (args[i].equals("--output-dir")) outputDir = args[++i];
            if (args[i].equals("--data-dir"))   dataDir   = args[++i];
        }
        new File(outputDir).mkdirs();

        System.out.println("=== Exp 4.5: Dirichlet Distribution Demonstration ===");

        List<String[]> rows = new ArrayList<>();
        rows.add(new String[]{"Query", "Source", "ResultCount", "SampleResult", "Status"});

        // Try to load TTL file
        String ttlPath = dataDir + "/exp4/exp4_dirichlet.ttl";
        Dataset ttlDs = loadTtl(ttlPath);
        String source = (ttlDs != null) ? "TTL-file" : "in-memory";

        // Fall back to in-memory dataset
        Dataset ds = (ttlDs != null) ? ttlDs : buildInMemoryDirDataset(50, 4);

        System.out.println("  Source: " + source);
        System.out.println();

        runQuery("Q-dir-1 (anomaly JSD)", source, ds, Q_DIR_1, rows);
        runQuery("Q-dir-2 (mean vector)", source, ds, Q_DIR_2, rows);
        runQuery("Q-dir-3 (CDF filter)",  source, ds, Q_DIR_3, rows);

        if (ttlDs != null) ttlDs.close();
        else ds.close();

        // Always also run in-memory to verify correctness
        if (ttlDs != null) {
            System.out.println("\n  (Also verifying in-memory dataset)");
            Dataset memDs = buildInMemoryDirDataset(20, 4);
            runQuery("Q-dir-1 (in-mem)", "in-memory", memDs, Q_DIR_1, rows);
            runQuery("Q-dir-2 (in-mem)", "in-memory", memDs, Q_DIR_2, rows);
            memDs.close();
        }

        writeCsv(outputDir + "/exp4_dirichlet_demo.csv", rows);
        System.out.println("\nResults → " + outputDir + "/exp4_dirichlet_demo.csv");
    }

    // -----------------------------------------------------------------------

    private static void runQuery(String label, String source, Dataset ds,
                                  String sparql, List<String[]> rows) {
        String status = "OK";
        int count = 0;
        String sample = "";
        try {
            Query q = QueryFactory.create(sparql);
            try (QueryExecution qe = QueryExecutionFactory.create(q, ds)) {
                ResultSet rs = qe.execSelect();
                List<String> resVars = rs.getResultVars();
                while (rs.hasNext()) {
                    QuerySolution row = rs.next();
                    count++;
                    if (count == 1) {
                        // collect component URI and first value
                        for (String var : resVars) {
                            if (row.get(var) != null) {
                                String v = row.get(var).toString();
                                if (sample.isEmpty()) sample = var + "=" + v;
                                else { sample += " | " + var + "=" + v; break; }
                            }
                        }
                    }
                }
            }
        } catch (Exception e) {
            status = "ERROR: " + e.getMessage();
        }
        System.out.printf("  %-30s  n=%3d  %s%n", label, count, status);
        if (!sample.isEmpty()) System.out.printf("    sample: %s%n", sample);
        rows.add(new String[]{label, source, String.valueOf(count), sample, status});
    }

    // -----------------------------------------------------------------------
    // In-memory Dirichlet dataset builder
    // -----------------------------------------------------------------------

    private static Dataset buildInMemoryDirDataset(int n, int k) {
        Model m = ModelFactory.createDefaultModel();
        Property hasMeasured = m.createProperty(NS_CFM + "hasMeasuredComposition");
        Property hasExpected  = m.createProperty(NS_CFM + "hasExpectedComposition");
        java.util.concurrent.ThreadLocalRandom rng = java.util.concurrent.ThreadLocalRandom.current();

        for (int i = 1; i <= n; i++) {
            Resource e = m.createResource(NS_EX + "component_" + String.format("%06d", i));
            String alphaM = makeDirJson(k, rng);
            String alphaE = makeSmoothedDirJson(k, rng, alphaM);
            e.addProperty(hasMeasured, m.createTypedLiteral(alphaM, NS_UQ + "dirichletLiteral"));
            e.addProperty(hasExpected, m.createTypedLiteral(alphaE, NS_UQ + "dirichletLiteral"));
        }
        return DatasetFactory.create(m);
    }

    private static String makeDirJson(int k, java.util.concurrent.ThreadLocalRandom rng) {
        StringBuilder sb = new StringBuilder("{\"alphas\":[");
        for (int i = 0; i < k; i++) {
            if (i > 0) sb.append(",");
            sb.append(String.format("%.4f", rng.nextDouble(0.5, 5.0)));
        }
        sb.append("]}");
        return sb.toString();
    }

    private static String makeSmoothedDirJson(int k, java.util.concurrent.ThreadLocalRandom rng,
                                               String measuredJson) {
        // Parse measured alpha and smooth toward uniform
        try {
            com.fasterxml.jackson.databind.ObjectMapper om = new com.fasterxml.jackson.databind.ObjectMapper();
            com.fasterxml.jackson.databind.JsonNode node = om.readTree(measuredJson);
            com.fasterxml.jackson.databind.JsonNode alphaNode = node.get("alphas");
            double[] alpha = new double[k];
            double sum = 0;
            for (int i = 0; i < k; i++) { alpha[i] = alphaNode.get(i).asDouble(); sum += alpha[i]; }
            double uniVal = sum / k;
            StringBuilder sb = new StringBuilder("{\"alphas\":[");
            for (int i = 0; i < k; i++) {
                if (i > 0) sb.append(",");
                double smoothed = 0.6 * alpha[i] + 0.4 * uniVal;
                sb.append(String.format("%.4f", smoothed));
            }
            sb.append("]}");
            return sb.toString();
        } catch (Exception e) {
            return makeDirJson(k, rng);
        }
    }

    // -----------------------------------------------------------------------

    private static Dataset loadTtl(String path) {
        File f = new File(path);
        if (!f.exists()) {
            System.out.printf("  (TTL not found: %s — will use in-memory)%n", path);
            return null;
        }
        try {
            Model m = ModelFactory.createDefaultModel();
            m.read(f.toURI().toString(), "TURTLE");
            return DatasetFactory.create(m);
        } catch (Exception e) {
            System.err.println("  ERROR loading " + path + ": " + e.getMessage());
            return null;
        }
    }

    private static void writeCsv(String path, List<String[]> rows) throws IOException {
        try (PrintWriter pw = new PrintWriter(new FileWriter(path))) {
            for (String[] row : rows)
                pw.println(String.join(",", Arrays.stream(row)
                        .map(s -> "\"" + s.replace("\"", "'") + "\"")
                        .toArray(String[]::new)));
        }
        System.out.println("CSV written: " + path);
    }
}
